[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF54L15"

[build]
target = "riscv32emc-unknown-none-elf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core", "compiler_builtins"]